
global:
  difficulty: easy
ak47:
  enabled: true
  quick_charge_level: 0
allays:
  enabled: true
amethyst:
  enabled: true
  probability: 0.15
angrygolems:
  enabled: true
anvil:
  enabled: true
  min_drop_height: 9
  max_drop_height: 20
  period: 15
axolotl:
  enabled: true
  radius: 24.0
bamboo:
  enabled: true
bedrock:
  enabled: true
bees:
  enabled: true
  probability: 0.1
  radius: 3
blazeeye:
  enabled: true
blazepower:
  enabled: true
blood:
  enabled: true
boatbomb:
  enabled: true
bouncyprojectile:
  enabled: true
  split_count: 2
  split_iterations: 1
bucketroulette:
  enabled: true
butterfingers:
  enabled: true
buttondrop:
  enabled: true
  max_uses: 10
cactuskick:
  enabled: true
cakes:
  enabled: true
  probability: 0.05
catbat:
  enabled: true
  probability: 1.0
chainmailrecipe:
  enabled: true
chargedcreeper:
  enabled: true
  diamond_count: 1
chestshuffle:
  enabled: true
chickens:
  enabled: true
  zombie_rider_chance: 0.02
classiclava:
  enabled: true
  normal_spread: 2
  nether_spread: 4
  end_spread: 0
cookies:
  enabled: true
creeperdeath:
  enabled: true
  allay_count: 1
deathscoreboard:
  enabled: true
demand:
  enabled: true
dirtrecipe:
  enabled: true
dirtstacks:
  enabled: true
  regular_probability: 0.2
  frequent_probability: 0.5
doctordances:
  enabled: true
doordrop:
  enabled: true
  max_uses: 32
dragonbomb:
  enabled: true
  min_timer_triggers_per_attack: 6
  max_timer_triggers_per_attack: 15
dripstone:
  enabled: true
drowned:
  enabled: true
  probability: 1.0
eggarrow:
  enabled: true
  probability: 1.0
eggdrop:
  enabled: true
  probability: 1.0
  min_eggs: 1
  max_eggs: 1
eggs:
  enabled: true
eggshells:
  enabled: true
encumbrance:
  enabled: true
  penalties:
    occupied_inventory_slot: 0.0002
    leather_armor: 0.0005
    non_leather_armor: 0.0005
    slowness: 0.01
    confusion: 0.01
    gods_rage: 0.001
endcrystal:
  enabled: true
enddirt:
  enabled: true
enderchest:
  enabled: true
endermangod:
  enabled: true
endermites:
  enabled: true
endspeed:
  enabled: true
escalation:
  enabled: true
  effect_count: 4
expirationdate:
  enabled: true
  probability: 0.05
  slime_size: 2
explosivearrow:
  enabled: true
fall:
  enabled: true
fishhook:
  enabled: true
  speed: 10.0
fishsanctuary:
  enabled: true
forestfire:
  enabled: true
freecookie:
  enabled: true
funhat:
  enabled: true
  probability: 0.1
ghastburn:
  enabled: true
ghastlava:
  enabled: true
ghasts:
  enabled: true
  probability: 0.1
glass:
  enabled: true
goddesshoe:
  enabled: true
grassspread:
  enabled: true
  probability: 0.5
gravestone:
  enabled: true
grievingwidow:
  enabled: true
  minutes_to_disable: 20
johnny:
  enabled: true
  probability: 0.01
killerrabbit:
  enabled: true
lavalaunch:
  enabled: true
  velocity_y: 1.2
learning:
  enabled: true
levitation:
  enabled: true
  levitation_seconds: 2
llamahunter:
  enabled: true
  speed_multiplier: 4.0
  min_llamas: 1
melompkin:
  enabled: true
mimics:
  enabled: true
  probability: 0.01
minecrafttrivia:
  enabled: true
  minutes_between_questions: 10
  minutes_to_answer: 2
moss:
  enabled: true
mossrevenge:
  enabled: true
  probability: 0.05
  slime_size: 2
namedzombie:
  enabled: true
  probability: 0.2
netherrack:
  enabled: true
  radius: 5
nodrops:
  enabled: true
nylium:
  enabled: true
oldage:
  enabled: true
  age_limit: 100 # NOTE: Read this in LearningFromFailureListener as well
overgrowth:
  enabled: true
  delay_seconds: 1200
  obsidian: false
parrotcookie:
  enabled: true
  parrot_duplicate_count: 2
parrotdeath:
  enabled: true
parrots:
  enabled: true
phantoms:
  enabled: true
  spawn_probability: 0.1
  cooldown_after_kill_seconds: 1200
  min_spawn_height: 6
  max_spawn_height: 20
piglins:
  enabled: true
pigs:
  enabled: true
pillagerdeath:
  enabled: true
  slime_count: 1
  slime_size: 2
pokeball:
  enabled: true
platefire:
  enabled: true
  probability: 0.01
pufferfish:
  enabled: true
  pufferfish_count: 3
  explosion_power: 4.0
  explosion_power_in_water: 8.0
pumpkins:
  enabled: true
rainwater:
  enabled: true
ravagers:
  enabled: true
  probability: 0.5
redstoneworld:
  enabled: true
  drop_probability: 0.2
  min_items: 1
  max_items: 16
  min_damage: 0.0
  max_damage: 10.0
sandattack:
  enabled: true
  red_sand_probability: 0.1
  max_drop_height: 15
sheepcolor:
  enabled: true
shieldsurf:
  enabled: true
  damage_multiplier: 0.1
shufflelogs:
  enabled: true
silverfish:
  enabled: true
  probability: 0.1
  bomb_probability: 0.1
  bomb_radius: 3
  release_chance: 0.1
  infestation_chance: 0.1
silverfishburn:
  enabled: true
slimesplit:
  enabled: true
  max_slime_size: 5
slowslab:
  enabled: true
  slow_time_seconds: 5
  slowness_level: 2
snowspeed:
  enabled: true
snowball:
  enabled: true
  speed_multiplier: 5.5
solidswap:
  enabled: true
spillage:
  enabled: true
stonetools:
  enabled: true
stronghold:
  enabled: true
  bomb_probability: 0.1
  bomb_radius: 3
  release_chance: 0.2
  infestation_chance: 0.2
sweetdreams:
  enabled: true
  effects_count: 1
tallgrass:
  enabled: true
  boots_damage_probability: 0.5
temperature:
  enabled: true
torches:
  enabled: true
trader:
  enabled: true
  chaos_trader_probability: 0.05
unfinished:
  enabled: true
villagerdeath:
  enabled: true
  leather_count: 1
wardensummon:
  enabled: true
weepingangel:
  enabled: true
  spawn_probability: 0.05
  max_angels_per_chunk: 1
  movement_speed: 0.5
witchattack:
  enabled: true
  probability: 0.5
witches:
  enabled: true
  probability: 0.01
witherarrow:
  enabled: true
  wither_seconds: 4
witherbow:
  enabled: true
  probability: 0.5
witherrose:
  enabled: true
witherskele:
  enabled: true
  probability: 1.0
zapwater:
  enabled: true
zombiedrowning:
  enabled: true
zombiespeed:
  enabled: true
  speed: 0.2738638
zombietrade:
  enabled: true
