
global:
  difficulty: hard
  suppress_protocollib_warning: false
  mirror_to_discordsrv: true
ak47:
  enabled: true
  quick_charge_level: 6
allays:
  enabled: true
amethyst:
  enabled: true
  probability: 0.08
angrygolems:
  enabled: true
anvil:
  enabled: true
  min_drop_height: 5 # NOTE: Read this in HeavyRainFeature as well
  max_drop_height: 15 # NOTE: Read this in HeavyRainFeature as well
  period: 8
apache:
  enabled: true
  probability: 0.25
axolotl:
  enabled: true
  radius: 64.0
bamboo:
  enabled: true
banishment:
  enabled: true
  probability: 0.03
bedrock:
  enabled: true
bees:
  enabled: true
  probability: 0.2
  radius: 6
  friendly_axe: true
birchglare:
  enabled: true
blazeeye:
  enabled: true
blazepower:
  enabled: true
blood:
  enabled: true
boatbomb:
  enabled: true
bouncyprojectile:
  enabled: true
  split_count: 3
  split_iterations: 2
bucketroulette:
  enabled: true
butterfingers:
  enabled: true
buttondrop:
  enabled: true
  max_uses: 3
cactuskick:
  enabled: true
cakes:
  enabled: true
  probability: 0.05
candyshop:
  enabled: true
carefulhands:
  enabled: true
  probability: 0.01
cataclysm:
  enabled: true
  radius: 7.0
catbat:
  enabled: true
  probability: 1.0
chainmailrecipe:
  enabled: true
chargedcreeper:
  enabled: true
  diamond_count: 1
chestshuffle:
  enabled: true
chickens:
  enabled: true
  zombie_rider_chance: 0.2
classiclava:
  enabled: true
  normal_spread: 6
  nether_spread: 12
  end_spread: 0
cookies:
  enabled: true
deathscoreboard:
  enabled: true
demand:
  enabled: true
  bowser_chance: 0.1
dirtrecipe:
  enabled: true
dirtstacks:
  enabled: true
  regular_probability: 0.5
  frequent_probability: 1.1
doctordances:
  enabled: true
doordrop:
  enabled: true
  max_uses: 12
dragonbomb:
  enabled: true
  min_timer_triggers_per_attack: 2
  max_timer_triggers_per_attack: 10
dripstone:
  enabled: true
drowned:
  enabled: true
  probability: 1.0
eggarrow:
  enabled: true
  probability: 1.0
eggdrop:
  enabled: true
  probability: 1.0
  min_eggs: 1
  max_eggs: 5
eggs:
  enabled: true
eggshells:
  enabled: true
encumbrance:
  enabled: true
  penalties:
    occupied_inventory_slot: 0.0004
    leather_armor: 0.0015
    non_leather_armor: 0.003
    slowness: 0.15
    confusion: 0.10
    gods_rage: 0.02
endcrystal:
  enabled: true
enddirt:
  enabled: true
enderchest:
  enabled: true
endermangod:
  enabled: true
endermites:
  enabled: true
endspeed:
  enabled: true
escalation:
  enabled: true
  effect_count: 4
expirationdate:
  enabled: true
  probability: 0.2
  slime_size: 2
explosivearrow:
  enabled: true
fall:
  enabled: true
feastupontheweak:
  enabled: true
fishhook:
  enabled: true
  speed: 20.0
fishsanctuary:
  enabled: true
forestfire:
  enabled: true
freecookie:
  enabled: true
funhat:
  enabled: true
  probability: 0.1
ghastburn:
  enabled: true
ghastlava:
  enabled: true
ghasts:
  enabled: true
  probability: 0.25
glass:
  enabled: true
goddesshoe:
  enabled: true
grassspread:
  enabled: true
  probability: 0.6
gravestone:
  enabled: true
grievingwidow:
  enabled: true
  minutes_to_disable: 8
heavyrain:
  enabled: true
  ticks_between_drops: 20
  drop_count: 30
johnny:
  enabled: true
  probability: 0.2
kamekschaos:
  enabled: true
killerrabbit:
  enabled: true
lavalaunch:
  enabled: true
  velocity_y: 1.9
learning:
  enabled: true
levitation:
  enabled: true
  levitation_seconds: 10
llamahunter:
  enabled: true
  speed_multiplier: 7.0
  min_llamas: 3
melompkin:
  enabled: true
mimics:
  enabled: true
  probability: 0.1
minecrafttrivia:
  enabled: true
  minutes_to_answer: 2
moss:
  enabled: true
mossrevenge:
  enabled: true
  probability: 0.3
  slime_size: 2
namedzombie:
  enabled: true
  probability: 0.2
netherrack:
  enabled: true
  radius: 5
nice:
  enabled: true
nodrops:
  enabled: true
nylium:
  enabled: true
obsidianwall:
  enabled: true
  wall_distance: 400
oldage:
  enabled: true
  age_limit: 100 # NOTE: Read this in LearningFromFailureListener as well
overgrowth:
  enabled: true
  delay_seconds: 450
  obsidian: true
parrotcookie:
  enabled: true
  parrot_duplicate_count: 6
parrotdeath:
  enabled: true
parrots:
  enabled: true
phantoms:
  enabled: true
  spawn_probability: 0.5
  cooldown_after_kill_seconds: 600
  min_spawn_height: 6
  max_spawn_height: 20
piglins:
  enabled: true
pigs:
  enabled: true
pillagerdeath:
  enabled: true
  slime_count: 4
  slime_size: 2
pokeball:
  enabled: true
platefire:
  enabled: true
  probability: 0.1
prisonersdilemma:
  enabled: true
pufferfish:
  enabled: true
  pufferfish_count: 6
  explosion_power: 6.0
  explosion_power_in_water: 12.0
pumpkins:
  enabled: true
rainwater:
  enabled: true
ravagers:
  enabled: true
  probability: 0.5
redstoneworld:
  enabled: true
  drop_probability: 0.5
  min_items: 1
  max_items: 64
  min_damage: 4.0
  max_damage: 30.0
sandattack:
  enabled: true
  red_sand_probability: 0.1
  max_drop_height: 15 # NOTE: Read this in SandstormFeature as well
sandblaster:
  enabled: true
  sand_radius: 10.0
sandstorm:
  enabled: true
  ticks_between_drops: 5
  drop_count: 120
serverfire:
  enabled: true
  radius: 7.0
  rolls: 20
sheepcolor:
  enabled: true
shieldsurf:
  enabled: true
  damage_multiplier: 2.0
shufflelogs:
  enabled: true
silverfish:
  enabled: true
  probability: 0.2
  bomb_probability: 0.4
  bomb_radius: 4
  release_chance: 0.3
  infestation_chance: 0.3
silverfishburn:
  enabled: true
sinkhole:
  enabled: true
  normal_chance: 0.4
  nether_chance: 0.6
  end_chance: 0.6
slimesplit:
  enabled: true
  max_slime_size: 10
slowslab:
  enabled: true
  slow_time_seconds: 15
  slowness_level: 4
snowspeed:
  enabled: true
snowball:
  enabled: true
  speed_multiplier: 5.5
solidswap:
  enabled: true
spatialrend:
  enabled: true
spillage:
  enabled: true
stonetools:
  enabled: true
stronghold:
  enabled: true
  bomb_probability: 0.2
  bomb_radius: 6
  release_chance: 0.5
  infestation_chance: 0.5
sweetdreams:
  enabled: true
  effects_count: 4
tallgrass:
  enabled: true
  boots_damage_probability: 1.0
temperature:
  enabled: true
torches:
  enabled: true
trader:
  enabled: true
  chaos_trader_probability: 0.05
unfinished:
  enabled: true
villagerdeath:
  enabled: true
  leather_count: 1
wardensummon:
  enabled: true
weepingangel:
  enabled: true
  spawn_probability: 0.05
  max_angels_per_chunk: 3
  movement_speed: 1.2
witchattack:
  enabled: true
  parrot_probability: 0.3
  allay_probability: 0.3
witches:
  enabled: true
  probability: 0.10
witherarrow:
  enabled: true
  wither_seconds: 15
witherbow:
  enabled: true
  probability: 0.5
witherrose:
  enabled: true
witherskele:
  enabled: true
  probability: 1.0
zapwater:
  enabled: true
zombiedrowning:
  enabled: true
zombiespeed:
  enabled: true
  speed: 0.2738638
zombietrade:
  enabled: true
