
# Welcome to the configuration for A Turtle's Troll! Here, you can
# tweak the various parameters of the plugin to your own personal
# preferences.
#
# The first thing you need to know is that there are four difficulty
# levels: easy, normal, hard, and insane. Your global.difficulty flag
# can be any of these four values. Any values in this file except
# those in the global.* namespace can be supplied with any of the
# following.
#
# * A concrete value of the required type. This will override all
#   difficulty settings.
#
# * The string "default" will pull from the global.difficulty
#   setting's default value for this field.
#
# * The string "easy", "normal", "hard", or "insane" will pull from
#   that particular difficulty setting's default value, regardless of
#   the value of global.difficulty.
#
# A missing field is equivalent to a field whose value is "default".
#
# NOTE: This is a plugin that's designed to be difficult and chaotic.
# If you play on "easy", "normal", or "hard" difficulty, the game is
# intended to be playable and winnable by a sufficiently skilled
# gamer. The "insane" difficulty is not intended to be playable. I
# just cranked all the difficulty settings up as high as I could. You
# will get killed. A lot. I have not playtested "insane" at all and I
# do not expect it to be playable.

global:
  # (String) The global difficulty. One of "easy", "normal", "hard",
  # or "insane". Any field outside of the global namespace whose value
  # is "default" will pull from the difficulty indicated here.
  difficulty: normal

# Pillagers spawn with a crossbow called "AK57".
ak47:
  enabled: default
  # (Integer) The level of Quick Charge the crossbow should have.
  quick_charge_level: default

# Allays automatically bond to the nearest player and have an infinite
# supply of flowers.
allays:
  enabled: default

# When an amethyst block is broken, there is a chance of dropping
# golden apples.
amethyst:
  enabled: default
  # (Float) The weight given to this event.
  probability: default

# Iron golems are always angry at the nearest player.
angrygolems:
  enabled: default

# If a player stands still for long enough, an anvil will drop on
# their head. Anvils can be smelted into iron nuggets.
anvil:
  enabled: default
  # (Integer) The minimum height at which the anvil will drop,
  # relative to the player.
  min_drop_height: default
  # (Integer) The maximum height at which the anvil will drop,
  # relative to the player. The anvil will fall from this height or
  # the nearest ceiling above the player, whichever is shorter.
  max_drop_height: default
  # (Integer) How often the anvil check is performed, in seconds.
  period: default

apache:
  enabled: default
  probability: default

# When an axolotl dies, the nearest player also dies.
axolotl:
  enabled: default
  # (Float) The maximum block distance from the axolotl to the player
  # affected by this. If no player is within this radius, no one dies.
  radius: default

# When bamboo grows, it has a chance to spread.
bamboo:
  enabled: default

# Certain blocks transform into bedrock when mined.
bedrock:
  enabled: default

# All wood blocks have a chance of spawning bees.
bees:
  enabled: default
  # (Float) The weight given to this event.
  probability: default
  # (Integer) The radius of wood blocks to turn into bees.
  radius: default

# Eyes of Blaze can be crafted from Flint & Steel and an Ender Pearl.
# These work like Eyes of Ender, but they only work in the Nether and
# find fortresses, not strongholds.
blazeeye:
  enabled: default

# Blazes spawn evokers during their attack sequence.
blazepower:
  enabled: default

# When a player takes damage, bluestone wire is placed at their feet.
blood:
  enabled: default

# If a boat hits the ground hard enough, it explodes.
boatbomb:
  enabled: default

# When an arrow hits a wall, it duplicates and bounces off it.
bouncyprojectile:
  enabled: default
  # (Integer) The number of duplicate arrows to make at each
  # collision.
  split_count: default
  # (Integer) The number of times a single arrow can duplicate.
  split_iterations: default

# Any bucket without a custom name will randomly change its contents
# every eight seconds.
bucketroulette:
  enabled: default

# If you open an inventory screen, the item in your main hand is
# dropped.
butterfingers:
  enabled: default

# Buttons in the world have durability and break after a certain
# number of uses.
buttondrop:
  enabled: default
  # (Integer) The number of uses before a button breaks.
  max_uses: default

# Looking at a cactus causes the player to be kicked.
cactuskick:
  enabled: default

# Cakes spawn in the wild and grant effects when eaten. Eating the
# last bite of a cake causes it to explode.
cakes:
  enabled: default
  # (Float) The probability of replacing a given mob spawn with a cake.
  probability: default

# When you mine a block, there's a small chance that the game treats
# you as though you had silk touch, even if you didn't.
carefulhands:
  enabled: default
  # (Float) The probability of this happening, from 0 to 1.
  probability: default

# Cats and bats transform into each other when killed.
catbat:
  enabled: default
  # (Float) The probability of this event occurring.
  probability: default

# Chainmail armor can be crafted from lava buckets.
chainmailrecipe:
  enabled: default

# Killing a charged creeper is guaranteed to drop diamonds.
chargedcreeper:
  enabled: default
  # (Integer) The number of diamonds to drop.
  diamond_count: default

# When you attempt to open a chest, a different nearby chest might
# accidentally be opened instead.
chestshuffle:
  enabled: default

# Chickens explode when they take damage for any reason. Several
# passive mob types are replaced with chickens. All chickens that
# spawn have a higher-than-usual chance of spawning with a baby zombie
# rider.
chickens:
  enabled: default
  # (Float) The chance that a baby zombie will spawn on a given
  # chicken, from 0 to 1.
  zombie_rider_chance: default

# Lava spreads further than usual.
classiclava:
  enabled: default
  # (Integer) The amount to increase lava spread in the overworld.
  normal_spread: default
  # (Integer) The amount to increase lava spread in the Nether.
  nether_spread: default
  # (Integer) The amount to increase lava spread in the End.
  end_spread: default

# Eating a cookie gives the player one of several effects at random.
cookies:
  enabled: default

# Killing a non-charged creeper summons allays. Exploding a
# non-charged creeper also summons allays.
creeperdeath:
  enabled: default
  # (Integer) The number of allays to spawn.
  allay_count: default

# A scoreboard shows on the right side of the screen, indicating the
# number of times each player has died.
deathscoreboard:
  enabled: default

# At dawn, a demand is made by the gods. If that demand is not met,
# then players are not permitted to sleep on the following night.
demand:
  enabled: default

# Nine dirt can be crafted into a stick. Nine sticks can be crafted
# into dirt.
dirtrecipe:
  enabled: default

# All blocks have a chance of dropping 64 dirt blocks instead of their
# intended drop.
dirtstacks:
  enabled: default
  # The weight given to this drop event, for normal blocks.
  regular_probability: default
  # The weight given to this drop event, for "special" blocks such as
  # ores.
  frequent_probability: default

# If a full Minecraft day goes by with no one dying, then every player
# receives a small reward.
doctordances:
  enabled: default

# Doors in the world have durability and break after a certain number
# of uses.
doordrop:
  enabled: default
  # (Integer) The number of uses before a door breaks.
  max_uses: default

# The Ender Dragon drops TNT at regular intervals. The Ender Dragon is
# immune to explosion damage.
dragonbomb:
  enabled: default
  min_timer_triggers_per_attack: default
  max_timer_triggers_per_attack: default

dripstone:
  enabled: default

drowned:
  enabled: default
  probability: default

eggarrow:
  enabled: default
  probability: default

eggdrop:
  enabled: default
  probability: default
  min_eggs: default
  max_eggs: default

eggs:
  enabled: default

eggshells:
  enabled: default

encumbrance:
  enabled: default
  penalties:
    occupied_inventory_slot: default
    leather_armor: default
    non_leather_armor: default
    slowness: default
    confusion: default
    gods_rage: default

endcrystal:
  enabled: default

enddirt:
  enabled: default

enderchest:
  enabled: default

endermangod:
  enabled: default

endermites:
  enabled: default

endspeed:
  enabled: default

escalation:
  enabled: default
  effect_count: default

expirationdate:
  enabled: default
  probability: default
  slime_size: default

explosivearrow:
  enabled: default

fall:
  enabled: default

fishhook:
  enabled: default
  speed: default

fishsanctuary:
  enabled: default

forestfire:
  enabled: default

freecookie:
  enabled: default

funhat:
  enabled: default
  probability: default

ghastburn:
  enabled: default

ghastlava:
  enabled: default

ghasts:
  enabled: default
  probability: default

glass:
  enabled: default

goddesshoe:
  enabled: default

grassspread:
  enabled: default
  probability: default

gravestone:
  enabled: default

grievingwidow:
  enabled: default
  minutes_to_disable: default

johnny:
  enabled: default
  probability: default

killerrabbit:
  enabled: default

lavalaunch:
  enabled: default
  velocity_y: default

learning:
  enabled: default

levitation:
  enabled: default
  levitation_seconds: default

llamahunter:
  enabled: default
  speed_multiplier: default
  min_llamas: default

melompkin:
  enabled: default

mimics:
  enabled: default
  probability: default

minecrafttrivia:
  enabled: default
  minutes_between_questions: default
  minutes_to_answer: default

moss:
  enabled: default

mossrevenge:
  enabled: default
  probability: default
  slime_size: default

namedzombie:
  enabled: default
  probability: default

netherrack:
  enabled: default
  radius: default

nodrops:
  enabled: default

nylium:
  enabled: default

oldage:
  enabled: default
  age_limit: default

overgrowth:
  enabled: default
  delay_seconds: default
  obsidian: default

parrotcookie:
  enabled: default
  parrot_duplicate_count: default

parrotdeath:
  enabled: default

parrots:
  enabled: default

phantoms:
  enabled: default
  spawn_probability: default
  cooldown_after_kill_seconds: default
  min_spawn_height: default
  max_spawn_height: default

piglins:
  enabled: default

pigs:
  enabled: default

pillagerdeath:
  enabled: default
  slime_count: default
  slime_size: default

pokeball:
  enabled: default

platefire:
  enabled: default
  probability: default

pufferfish:
  enabled: default
  pufferfish_count: default
  explosion_power: default
  explosion_power_in_water: default

pumpkins:
  enabled: default

rainwater:
  enabled: default

ravagers:
  enabled: default
  probability: default

redstoneworld:
  enabled: default
  drop_probability: default
  min_items: default
  max_items: default
  min_damage: default
  max_damage: default

sandattack:
  enabled: default
  red_sand_probability: default
  max_drop_height: default

sheepcolor:
  enabled: default

shieldsurf:
  enabled: default
  damage_multiplier: default

shufflelogs:
  enabled: default

silverfish:
  enabled: default
  probability: default
  bomb_probability: default
  bomb_radius: default
  release_chance: default
  infestation_chance: default

silverfishburn:
  enabled: default

slimesplit:
  enabled: default
  max_slime_size: default

slowslab:
  enabled: default
  slow_time_seconds: default
  slowness_level: default

snowspeed:
  enabled: default

snowball:
  enabled: default
  speed_multiplier: default

solidswap:
  enabled: default

spillage:
  enabled: default

stonetools:
  enabled: default

stronghold:
  enabled: default
  bomb_probability: default
  bomb_radius: default
  release_chance: default
  infestation_chance: default

sweetdreams:
  enabled: default
  effects_count: default

tallgrass:
  enabled: default
  boots_damage_probability: default

temperature:
  enabled: default

torches:
  enabled: default

trader:
  enabled: default
  chaos_trader_probability: default

unfinished:
  enabled: default

villagerdeath:
  enabled: default
  leather_count: default

wardensummon:
  enabled: default

weepingangel:
  enabled: default
  spawn_probability: default
  max_angels_per_chunk: default
  movement_speed: default

witchattack:
  enabled: default
  probability: default

witches:
  enabled: default
  probability: default

witherarrow:
  enabled: default
  wither_seconds: default

witherbow:
  enabled: default
  probability: default

witherrose:
  enabled: default

witherskele:
  enabled: default
  probability: default

zapwater:
  enabled: default

zombiedrowning:
  enabled: default

zombiespeed:
  enabled: default
  speed: default

zombietrade:
  enabled: default
