
global:
  difficulty: normal
allays:
  enabled: true
amethyst:
  enabled: true
  probability: 0.1
angrygolems:
  enabled: true
anvil:
  enabled: true
  min_drop_height: 7
  max_drop_height: 15
  period: 10 # In seconds
axolotl:
  enabled: true
  radius: 32
bamboo:
  enabled: true
bedrock:
  enabled: true
bees:
  enabled: true
  probability: 0.2
  radius: 5
blazepower:
  enabled: true
boatbomb:
  enabled: true
bucketroulette:
  enabled: true
dirtstacks:
  enabled: true
  regular_probability: 0.3
  frequent_probability: 1.0
endermites:
  enabled: true
melompkin:
  enabled: true
mossrevenge:
  enabled: true
  probability: 0.2
  slime_size: 2
netherrack:
  enabled: true
  radius: 5
nodrops:
  enabled: true
shufflelogs:
  enabled: true
silverfish:
  enabled: true
  probability: 0.2
  radius: 3
  release_chance: 0.2
  infestation_chance: 0.2 # NOTE: Stack on release_chance in the code
stronghold:
  enabled: true
  radius: 4
  release_chance: 0.5
  infestation_chance: 0.5
