
global:
  difficulty: normal
  suppress_protocollib_warning: false
  mirror_to_discordsrv: true
ak47:
  enabled: true
  quick_charge_level: 5
allays:
  enabled: true
amethyst:
  enabled: true
  probability: 0.1
angrygolems:
  enabled: true
anvil:
  enabled: true
  min_drop_height: 7 # NOTE: Read this in HeavyRainFeature as well
  max_drop_height: 15 # NOTE: Read this in HeavyRainFeature as well
  period: 10
apache:
  enabled: true
  probability: 0.25
axolotl:
  enabled: true
  radius: 32.0
bamboo:
  enabled: true
banishment:
  enabled: true
  probability: 0.02
bedrock:
  enabled: true
bees:
  enabled: true
  probability: 0.2
  radius: 5
  friendly_axe: true
birchglare:
  enabled: true
blazeeye:
  enabled: true
blazepower:
  enabled: true
blood:
  enabled: true
boatbomb:
  enabled: true
bouncyprojectile:
  enabled: true
  split_count: 2
  split_iterations: 2
bucketroulette:
  enabled: true
butterfingers:
  enabled: true
buttondrop:
  enabled: true
  max_uses: 4
cactuskick:
  enabled: true
cakes:
  enabled: true
  probability: 0.05
carefulhands:
  enabled: true
  probability: 0.01
cataclysm:
  enabled: true
  radius: 5.0
catbat:
  enabled: true
  probability: 1.0
chainmailrecipe:
  enabled: true
chargedcreeper:
  enabled: true
  diamond_count: 1
chestshuffle:
  enabled: true
chickenlay:
  enabled: true
  chance: 0.15
chickens:
  enabled: true
  zombie_rider_chance: 0.1
classiclava:
  enabled: true
  normal_spread: 4
  nether_spread: 8
  end_spread: 0
cookies:
  enabled: true
deathscoreboard:
  enabled: true
demand:
  enabled: true
  bowser_chance: 0.1
dirtrecipe:
  enabled: true
dirtstacks:
  enabled: true
  regular_probability: 0.3
  frequent_probability: 1.0
doctordances:
  enabled: true
doordrop:
  enabled: true
  max_uses: 16
dragonbomb:
  enabled: true
  min_timer_triggers_per_attack: 3
  max_timer_triggers_per_attack: 12
dripstone:
  enabled: true
drowned:
  enabled: true
  probability: 1.0
eggarrow:
  enabled: true
  probability: 1.0
eggdrop:
  enabled: true
  probability: 1.0
  min_eggs: 1
  max_eggs: 4
eggs:
  enabled: true
eggshells:
  enabled: true
encumbrance:
  enabled: true
  penalties:
    occupied_inventory_slot: 0.0003
    leather_armor: 0.001
    non_leather_armor: 0.0025
    slowness: 0.10
    confusion: 0.05
    jump_boost: 0.05
    gods_rage: 0.01
endcrystal:
  enabled: true
enddirt:
  enabled: true
enderchest:
  enabled: true
endermangod:
  enabled: true
endermites:
  enabled: true
endspeed:
  enabled: true
escalation:
  enabled: true
  effect_count: 4
expirationdate:
  enabled: true
  probability: 0.1
  slime_size: 2
explosivearrow:
  enabled: true
fall:
  enabled: true
feastupontheweak:
  enabled: true
fishhook:
  enabled: true
  speed: 15.0
fishsanctuary:
  enabled: true
forestfire:
  enabled: true
freecookie:
  enabled: true
funhat:
  enabled: true
  probability: 0.1
ghastburn:
  enabled: true
ghastlava:
  enabled: true
ghasts:
  enabled: true
  probability: 0.2
glass:
  enabled: true
goddesshoe:
  enabled: true
grassspread:
  enabled: true
  probability: 0.5
gravestone:
  enabled: true
grievingwidow:
  enabled: true
  minutes_to_disable: 10
happyrain:
  enabled: true
  drop_probability: 0.1
  drop_period: 15
heavyrain:
  enabled: true
  ticks_between_drops: 40
  drop_count: 10
horny:
  enabled: true
johnny:
  enabled: true
  probability: 0.1
kamekschaos:
  enabled: true
killerrabbit:
  enabled: true
lavalaunch:
  enabled: true
  velocity_y: 1.3
learning:
  enabled: true
levitation:
  enabled: true
  levitation_seconds: 5
llamahunter:
  enabled: true
  speed_multiplier: 5.5
  min_llamas: 2
melompkin:
  enabled: true
mimics:
  enabled: true
  probability: 0.05
minecrafttrivia:
  enabled: true
  minutes_to_answer: 2
moss:
  enabled: true
mossrevenge:
  enabled: true
  probability: 0.2
  slime_size: 2
namedzombie:
  enabled: true
  probability: 0.2
netherrack:
  enabled: true
  radius: 5
nice:
  enabled: true
nodrops:
  enabled: true
noyou:
  enabled: true
  odds: 1000000
nylium:
  enabled: true
obsidianwall:
  enabled: true
  wall_distance: 400
oldage:
  enabled: true
  age_limit: 100 # NOTE: Read this in LearningFromFailureListener as well
overgrowth:
  enabled: true
  delay_seconds: 600
  obsidian: false
parrotcookie:
  enabled: true
  parrot_duplicate_count: 5
parrotdeath:
  enabled: true
parrots:
  enabled: true
phantoms:
  enabled: true
  spawn_probability: 0.33
  cooldown_after_kill_seconds: 600
  min_spawn_height: 6
  max_spawn_height: 20
piglins:
  enabled: true
pigs:
  enabled: true
pillagerdeath:
  enabled: true
  slime_count: 3
  slime_size: 2
pokeball:
  enabled: true
pottery:
  enabled: true
  replace_chance: 0.05
  infected_chance: 0.1
platefire:
  enabled: true
  probability: 0.05
prisonersdilemma:
  enabled: true
pufferfish:
  enabled: true
  pufferfish_count: 5
  explosion_power: 5.0
  explosion_power_in_water: 10.0
pumpkins:
  enabled: true
rainwater:
  enabled: true
ravagers:
  enabled: true
  probability: 0.5
redstoneworld:
  enabled: true
  drop_probability: 0.5
  min_items: 1
  max_items: 64
  min_damage: 0.0
  max_damage: 20.0
sandattack:
  enabled: true
  red_sand_probability: 0.1
  max_drop_height: 15 # NOTE: Read this in SandstormFeature as well
sandblaster:
  enabled: true
  sand_radius: 6.0
sandstorm:
  enabled: true
  ticks_between_drops: 5
  drop_count: 120
serverfire:
  enabled: true
  radius: 6.0
  rolls: 10
sheepcolor:
  enabled: true
shieldsurf:
  enabled: true
  damage_multiplier: 1.0
shufflelogs:
  enabled: true
silverfish:
  enabled: true
  probability: 0.2
  bomb_probability: 0.2
  bomb_radius: 3
  release_chance: 0.2
  infestation_chance: 0.2 # NOTE: Stack on release_chance in the code
silverfishburn:
  enabled: true
sinkhole:
  enabled: true
  normal_chance: 0.2
  nether_chance: 0.4
  end_chance: 0.4
slimesplit:
  enabled: true
  max_slime_size: 10 # NOTE: Put a cap on this in the code
slowslab:
  enabled: true
  slow_time_seconds: 10
  slowness_level: 4
snowspeed:
  enabled: true
snowball:
  enabled: true
  speed_multiplier: 5.5
solidswap:
  enabled: true
spatialrend:
  enabled: true
spillage:
  enabled: true
sponges:
  enabled: true
stonetools:
  enabled: true
stronghold:
  enabled: true
  bomb_probability: 0.2
  bomb_radius: 4
  release_chance: 0.5
  infestation_chance: 0.5
sweetdreams:
  enabled: true
  effects_count: 3
tacticaldirt:
  enabled: true
tallgrass:
  enabled: true
  boots_damage_probability: 1.0
temperature:
  enabled: true
torches:
  enabled: true
trader:
  enabled: true
  chaos_trader_probability: 0.05
unfinished:
  enabled: true
villagerdeath:
  enabled: true
  leather_count: 1
wardensummon:
  enabled: true
weepingangel:
  enabled: true
  spawn_probability: 0.05
  max_angels_per_chunk: 2
  movement_speed: 1.0 # Meters per tick
whitedirt:
  enabled: true
  chance: 0.01
witchattack:
  enabled: true
  parrot_probability: 0.25
  allay_probability: 0.25
witches:
  enabled: true
  probability: 0.05
witherarrow:
  enabled: true
  wither_seconds: 10
witherbow:
  enabled: true
  probability: 0.5
witherrose:
  enabled: true
witherskele:
  enabled: true
  probability: 1.0
zapwater:
  enabled: true
zombiedrowning:
  enabled: true
zombiespeed:
  enabled: true
  speed: 0.2738638
zombietrade:
  enabled: true
