
global:
  difficulty: insane
  suppress_protocollib_warning: false
  mirror_to_discordsrv: true
ak47:
  enabled: true
  quick_charge_level: 10
allays:
  enabled: true
amethyst:
  enabled: true
  probability: 0.08
angrygolems:
  enabled: true
anvil:
  enabled: true
  min_drop_height: 4 # NOTE: Read this in HeavyRainFeature as well
  max_drop_height: 15 # NOTE: Read this in HeavyRainFeature as well
  period: 2
apache:
  enabled: true
  probability: 0.5
axolotl:
  enabled: true
  radius: 9999.0
bamboo:
  enabled: true
banishment:
  enabled: true
  probability: 0.10
bedrock:
  enabled: true
bees:
  enabled: true
  probability: 1.0
  radius: 10
  friendly_axe: false
birchglare:
  enabled: true
blazeeye:
  enabled: true
blazepower:
  enabled: true
blood:
  enabled: true
boatbomb:
  enabled: true
bouncyprojectile:
  enabled: true
  split_count: 3
  split_iterations: 4
bucketroulette:
  enabled: true
butterfingers:
  enabled: true
buttondrop:
  enabled: true
  max_uses: 1
cactuskick:
  enabled: true
cakes:
  enabled: true
  probability: 0.05
carefulhands:
  enabled: true
  probability: 0.01
cataclysm:
  enabled: true
  radius: 11.0
catbat:
  enabled: true
  probability: 1.0
chainmailrecipe:
  enabled: true
chargedcreeper:
  enabled: true
  diamond_count: 1
chestshuffle:
  enabled: true
chickens:
  enabled: true
  zombie_rider_chance: 1.0
classiclava:
  enabled: true
  normal_spread: 20
  nether_spread: 20
  end_spread: 0
cookies:
  enabled: true
deathscoreboard:
  enabled: true
demand:
  enabled: true
  bowser_chance: 0.1
dirtrecipe:
  enabled: true
dirtstacks:
  enabled: true
  regular_probability: 1.0
  frequent_probability: 2.0
doctordances:
  enabled: true
doordrop:
  enabled: true
  max_uses: 1
dragonbomb:
  enabled: true
  min_timer_triggers_per_attack: 1
  max_timer_triggers_per_attack: 1
dripstone:
  enabled: true
drowned:
  enabled: true
  probability: 1.0
eggarrow:
  enabled: true
  probability: 1.0
eggdrop:
  enabled: true
  probability: 1.0
  min_eggs: 16
  max_eggs: 16
eggs:
  enabled: true
eggshells:
  enabled: true
encumbrance:
  enabled: true
  penalties:
    occupied_inventory_slot: 0.001
    leather_armor: 0.05
    non_leather_armor: 0.05
    slowness: 1.00
    confusion: 1.00
    gods_rage: 1.00
endcrystal:
  enabled: true
enddirt:
  enabled: true
enderchest:
  enabled: true
endermangod:
  enabled: true
endermites:
  enabled: true
endspeed:
  enabled: true
escalation:
  enabled: true
  effect_count: 1
expirationdate:
  enabled: true
  probability: 1.0
  slime_size: 2
explosivearrow:
  enabled: true
fall:
  enabled: true
feastupontheweak:
  enabled: true
fishhook:
  enabled: true
  speed: 100.0
fishsanctuary:
  enabled: true
forestfire:
  enabled: true
freecookie:
  enabled: true
funhat:
  enabled: true
  probability: 0.1
ghastburn:
  enabled: true
ghastlava:
  enabled: true
ghasts:
  enabled: true
  probability: 0.25
glass:
  enabled: true
goddesshoe:
  enabled: true
grassspread:
  enabled: true
  probability: 0.9
gravestone:
  enabled: true
grievingwidow:
  enabled: true
  minutes_to_disable: 5
happyrain:
  enabled: true
  drop_probability: 0.5
  drop_period: 3
heavyrain:
  enabled: true
  ticks_between_drops: 15
  drop_count: 40
johnny:
  enabled: true
  probability: 0.9
kamekschaos:
  enabled: true
killerrabbit:
  enabled: true
lavalaunch:
  enabled: true
  velocity_y: 10.0
learning:
  enabled: true
levitation:
  enabled: true
  levitation_seconds: 600
llamahunter:
  enabled: true
  speed_multiplier: 20.0
  min_llamas: 5
melompkin:
  enabled: true
mimics:
  enabled: true
  probability: 0.1
minecrafttrivia:
  enabled: true
  minutes_to_answer: 2
moss:
  enabled: true
mossrevenge:
  enabled: true
  probability: 1.0
  slime_size: 2
namedzombie:
  enabled: true
  probability: 0.2
netherrack:
  enabled: true
  radius: 10
nice:
  enabled: true
nodrops:
  enabled: true
nylium:
  enabled: true
obsidianwall:
  enabled: true
  wall_distance: 400
oldage:
  enabled: true
  age_limit: 2
overgrowth:
  enabled: true
  delay_seconds: 10
  obsidian: true
parrotcookie:
  enabled: true
  parrot_duplicate_count: 20
parrotdeath:
  enabled: true
parrots:
  enabled: true
phantoms:
  enabled: true
  spawn_probability: 1.0
  cooldown_after_kill_seconds: 5
  min_spawn_height: 6
  max_spawn_height: 20
piglins:
  enabled: true
pigs:
  enabled: true
pillagerdeath:
  enabled: true
  slime_count: 6
  slime_size: 2
pokeball:
  enabled: true
platefire:
  enabled: true
  probability: 1.0
prisonersdilemma:
  enabled: true
pufferfish:
  enabled: true
  pufferfish_count: 10
  explosion_power: 20.0
  explosion_power_in_water: 40.0
pumpkins:
  enabled: true
rainwater:
  enabled: true
ravagers:
  enabled: true
  probability: 0.5
redstoneworld:
  enabled: true
  drop_probability: 1.0
  min_items: 64
  max_items: 64
  min_damage: 30.0
  max_damage: 60.0
sandattack:
  enabled: true
  red_sand_probability: 0.5
  max_drop_height: 15 # NOTE: Read this in SandstormFeature as well
sandblaster:
  enabled: true
  sand_radius: 20.0
sandstorm:
  enabled: true
  ticks_between_drops: 240
  drop_count: 3
serverfire:
  enabled: true
  radius: 20.0
  rolls: 100
sheepcolor:
  enabled: true
shieldsurf:
  enabled: true
  damage_multiplier: 2.0
shufflelogs:
  enabled: true
silverfish:
  enabled: true
  probability: 1.0
  bomb_probability: 1.0
  bomb_radius: 6
  release_chance: 0.5
  infestation_chance: 0.5
silverfishburn:
  enabled: true
sinkhole:
  enabled: true
  normal_chance: 1.0
  nether_chance: 1.0
  end_chance: 1.0
slimesplit:
  enabled: true
  max_slime_size: 15
slowslab:
  enabled: true
  slow_time_seconds: 999
  slowness_level: 5
snowspeed:
  enabled: true
snowball:
  enabled: true
  speed_multiplier: 20.0
solidswap:
  enabled: true
spatialrend:
  enabled: true
spillage:
  enabled: true
stonetools:
  enabled: true
stronghold:
  enabled: true
  bomb_probability: 1.0
  bomb_radius: 6
  release_chance: 0.5
  infestation_chance: 0.5
sweetdreams:
  enabled: true
  effects_count: 4
tacticaldirt:
  enabled: true
tallgrass:
  enabled: true
  boots_damage_probability: 1.0
temperature:
  enabled: true
torches:
  enabled: true
trader:
  enabled: true
  chaos_trader_probability: 0.5
unfinished:
  enabled: true
villagerdeath:
  enabled: true
  leather_count: 1
wardensummon:
  enabled: true
weepingangel:
  enabled: true
  spawn_probability: 0.1
  max_angels_per_chunk: 6
  movement_speed: 3.0
witchattack:
  enabled: true
  parrot_probability: 0.2
  allay_probability: 0.4
witches:
  enabled: true
  probability: 1.0
witherarrow:
  enabled: true
  wither_seconds: 999
witherbow:
  enabled: true
  probability: 0.5
witherrose:
  enabled: true
witherskele:
  enabled: true
  probability: 1.0
zapwater:
  enabled: true
zombiedrowning:
  enabled: true
zombiespeed:
  enabled: true
  speed: 4.0
zombietrade:
  enabled: true
