main: com.mercerenies.turtletroll.Main
name: A_Turtles_Troll
version: 1.20
api-version: 1.19
author: Mercerenies
description: Have fun :)
commands:
  turtle:
    description: Enable or disable features of A Turtle's Troll
    usage: /turtle <subcommand> [args...]
permissions:
  com.mercerenies.turtletroll.command:
    default: true
  com.mercerenies.turtletroll.command.bedtime:
    default: true
  com.mercerenies.turtletroll.feature.list:
    default: true
  com.mercerenies.turtletroll.feature.describe:
    default: true
  com.mercerenies.turtletroll.feature.toggle:
    default: op
  com.mercerenies.turtletroll.feature.debug:
    default: op
