main: com.mercerenies.turtletroll.TurtleTrollPlugin
name: A_Turtles_Troll
version: "1.24"
api-version: "1.19"
author: Mercerenies
description: Have fun :)
load: STARTUP
depend:
  - ProtocolLib
commands:
  turtle:
    description: Enable or disable features of A Turtle's Troll
    usage: /turtle <subcommand> [args...]
permissions:
  com.mercerenies.turtletroll.command:
    default: true
  com.mercerenies.turtletroll.command.demand:
    default: true
  com.mercerenies.turtletroll.command.encumbrance:
    default: true
  com.mercerenies.turtletroll.command.answer:
    default: true
  com.mercerenies.turtletroll.feature.list:
    default: true
  com.mercerenies.turtletroll.feature.describe:
    default: true
  com.mercerenies.turtletroll.feature.toggle:
    default: op
  com.mercerenies.turtletroll.debug:
    default: op
