
package com.mercerenies.turtletroll

import org.bukkit.Material

object BlockTypes {

  val GLASS = setOf(
      Material.BLACK_STAINED_GLASS, Material.BLACK_STAINED_GLASS_PANE, Material.BLUE_STAINED_GLASS,
      Material.BLUE_STAINED_GLASS_PANE, Material.BROWN_STAINED_GLASS,
      Material.BROWN_STAINED_GLASS_PANE, Material.CYAN_STAINED_GLASS,
      Material.CYAN_STAINED_GLASS_PANE, Material.GLASS, Material.GLASS_PANE,
      Material.GRAY_STAINED_GLASS, Material.GRAY_STAINED_GLASS_PANE, Material.GREEN_STAINED_GLASS,
      Material.GREEN_STAINED_GLASS_PANE, Material.LIGHT_BLUE_STAINED_GLASS,
      Material.LIGHT_BLUE_STAINED_GLASS_PANE, Material.LIGHT_GRAY_STAINED_GLASS,
      Material.LIGHT_GRAY_STAINED_GLASS_PANE, Material.LIME_STAINED_GLASS,
      Material.LIME_STAINED_GLASS_PANE, Material.MAGENTA_STAINED_GLASS,
      Material.MAGENTA_STAINED_GLASS_PANE, Material.ORANGE_STAINED_GLASS,
      Material.ORANGE_STAINED_GLASS_PANE, Material.PINK_STAINED_GLASS,
      Material.PINK_STAINED_GLASS_PANE, Material.PURPLE_STAINED_GLASS,
      Material.PURPLE_STAINED_GLASS_PANE, Material.RED_STAINED_GLASS,
      Material.RED_STAINED_GLASS_PANE, Material.TINTED_GLASS, Material.WHITE_STAINED_GLASS,
      Material.WHITE_STAINED_GLASS_PANE, Material.YELLOW_STAINED_GLASS,
      Material.YELLOW_STAINED_GLASS_PANE,
    )

  val TALL_GRASS = setOf(
    Material.GRASS, Material.TALL_GRASS, Material.FERN,
    Material.LARGE_FERN, Material.DEAD_BUSH, Material.CRIMSON_ROOTS, Material.WARPED_ROOTS,
  )

}
