
package com.mercerenies.turtletroll

import org.bukkit.Material

object BlockTypes {

  val GLASS = setOf(
    Material.BLACK_STAINED_GLASS, Material.BLACK_STAINED_GLASS_PANE, Material.BLUE_STAINED_GLASS,
    Material.BLUE_STAINED_GLASS_PANE, Material.BROWN_STAINED_GLASS,
    Material.BROWN_STAINED_GLASS_PANE, Material.CYAN_STAINED_GLASS,
    Material.CYAN_STAINED_GLASS_PANE, Material.GLASS, Material.GLASS_PANE,
    Material.GRAY_STAINED_GLASS, Material.GRAY_STAINED_GLASS_PANE, Material.GREEN_STAINED_GLASS,
    Material.GREEN_STAINED_GLASS_PANE, Material.LIGHT_BLUE_STAINED_GLASS,
    Material.LIGHT_BLUE_STAINED_GLASS_PANE, Material.LIGHT_GRAY_STAINED_GLASS,
    Material.LIGHT_GRAY_STAINED_GLASS_PANE, Material.LIME_STAINED_GLASS,
    Material.LIME_STAINED_GLASS_PANE, Material.MAGENTA_STAINED_GLASS,
    Material.MAGENTA_STAINED_GLASS_PANE, Material.ORANGE_STAINED_GLASS,
    Material.ORANGE_STAINED_GLASS_PANE, Material.PINK_STAINED_GLASS,
    Material.PINK_STAINED_GLASS_PANE, Material.PURPLE_STAINED_GLASS,
    Material.PURPLE_STAINED_GLASS_PANE, Material.RED_STAINED_GLASS,
    Material.RED_STAINED_GLASS_PANE, Material.TINTED_GLASS, Material.WHITE_STAINED_GLASS,
    Material.WHITE_STAINED_GLASS_PANE, Material.YELLOW_STAINED_GLASS,
    Material.YELLOW_STAINED_GLASS_PANE,
  )

  val TALL_GRASS = setOf(
    Material.GRASS, Material.TALL_GRASS, Material.FERN,
    Material.LARGE_FERN, Material.DEAD_BUSH, Material.CRIMSON_ROOTS, Material.WARPED_ROOTS,
  )

  val ORES = setOf(
    Material.COAL_ORE, Material.IRON_ORE, Material.LAPIS_ORE,
    Material.GOLD_ORE, Material.DIAMOND_ORE, Material.EMERALD_ORE,
    Material.NETHER_QUARTZ_ORE, Material.NETHER_GOLD_ORE, Material.ANCIENT_DEBRIS,
    Material.COPPER_ORE, Material.DEEPSLATE_COAL_ORE, Material.DEEPSLATE_COPPER_ORE,
    Material.DEEPSLATE_DIAMOND_ORE, Material.DEEPSLATE_EMERALD_ORE, Material.DEEPSLATE_GOLD_ORE,
    Material.DEEPSLATE_IRON_ORE, Material.DEEPSLATE_LAPIS_ORE, Material.DEEPSLATE_REDSTONE_ORE,
  )

  val SLABS = setOf(
    Material.ACACIA_SLAB, Material.ANDESITE_SLAB, Material.BIRCH_SLAB, Material.BLACKSTONE_SLAB,
    Material.BRICK_SLAB, Material.COBBLESTONE_SLAB, Material.CRIMSON_SLAB,
    Material.CUT_RED_SANDSTONE_SLAB, Material.CUT_SANDSTONE_SLAB, Material.DARK_OAK_SLAB,
    Material.DARK_PRISMARINE_SLAB, Material.DIORITE_SLAB, Material.END_STONE_BRICK_SLAB,
    Material.GRANITE_SLAB, Material.JUNGLE_SLAB, Material.MOSSY_COBBLESTONE_SLAB,
    Material.MOSSY_STONE_BRICK_SLAB, Material.NETHER_BRICK_SLAB, Material.OAK_SLAB,
    Material.PETRIFIED_OAK_SLAB, Material.POLISHED_ANDESITE_SLAB,
    Material.POLISHED_BLACKSTONE_BRICK_SLAB, Material.POLISHED_BLACKSTONE_SLAB,
    Material.POLISHED_DIORITE_SLAB, Material.POLISHED_GRANITE_SLAB,
    Material.PRISMARINE_BRICK_SLAB, Material.PRISMARINE_SLAB, Material.PURPUR_SLAB,
    Material.QUARTZ_SLAB, Material.RED_NETHER_BRICK_SLAB, Material.RED_SANDSTONE_SLAB,
    Material.SANDSTONE_SLAB, Material.SMOOTH_QUARTZ_SLAB, Material.SMOOTH_RED_SANDSTONE_SLAB,
    Material.SMOOTH_SANDSTONE_SLAB, Material.SMOOTH_STONE_SLAB, Material.SPRUCE_SLAB,
    Material.STONE_BRICK_SLAB, Material.STONE_SLAB, Material.WARPED_SLAB,
    Material.COBBLED_DEEPSLATE_SLAB, Material.CUT_COPPER_SLAB, Material.DEEPSLATE_BRICK_SLAB,
    Material.DEEPSLATE_TILE_SLAB, Material.EXPOSED_CUT_COPPER_SLAB,
    Material.OXIDIZED_CUT_COPPER_SLAB, Material.POLISHED_DEEPSLATE_SLAB,
    Material.WAXED_CUT_COPPER_SLAB, Material.WAXED_EXPOSED_CUT_COPPER_SLAB,
    Material.WAXED_OXIDIZED_CUT_COPPER_SLAB, Material.WEATHERED_CUT_COPPER_SLAB,
    Material.MANGROVE_SLAB,
  )

  val STAIRS = setOf(
    Material.ACACIA_STAIRS, Material.ANDESITE_STAIRS, Material.BIRCH_STAIRS,
    Material.BLACKSTONE_STAIRS, Material.BRICK_STAIRS, Material.COBBLESTONE_STAIRS,
    Material.CRIMSON_STAIRS, Material.DARK_OAK_STAIRS,
    Material.DARK_PRISMARINE_STAIRS, Material.DIORITE_STAIRS, Material.END_STONE_BRICK_STAIRS,
    Material.GRANITE_STAIRS, Material.JUNGLE_STAIRS, Material.MOSSY_COBBLESTONE_STAIRS,
    Material.MOSSY_STONE_BRICK_STAIRS, Material.NETHER_BRICK_STAIRS, Material.OAK_STAIRS,
    Material.POLISHED_ANDESITE_STAIRS,
    Material.POLISHED_BLACKSTONE_BRICK_STAIRS, Material.POLISHED_BLACKSTONE_STAIRS,
    Material.POLISHED_DIORITE_STAIRS, Material.POLISHED_GRANITE_STAIRS,
    Material.PRISMARINE_BRICK_STAIRS, Material.PRISMARINE_STAIRS, Material.PURPUR_STAIRS,
    Material.QUARTZ_STAIRS, Material.RED_NETHER_BRICK_STAIRS, Material.RED_SANDSTONE_STAIRS,
    Material.SANDSTONE_STAIRS, Material.SMOOTH_QUARTZ_STAIRS, Material.SMOOTH_RED_SANDSTONE_STAIRS,
    Material.SMOOTH_SANDSTONE_STAIRS, Material.SPRUCE_STAIRS,
    Material.STONE_BRICK_STAIRS, Material.STONE_STAIRS, Material.WARPED_STAIRS,
    Material.COBBLED_DEEPSLATE_STAIRS, Material.CUT_COPPER_STAIRS, Material.DEEPSLATE_BRICK_STAIRS,
    Material.DEEPSLATE_TILE_STAIRS, Material.EXPOSED_CUT_COPPER_STAIRS,
    Material.OXIDIZED_CUT_COPPER_STAIRS, Material.POLISHED_DEEPSLATE_STAIRS,
    Material.WAXED_CUT_COPPER_STAIRS, Material.WAXED_EXPOSED_CUT_COPPER_STAIRS,
    Material.WAXED_OXIDIZED_CUT_COPPER_STAIRS, Material.WEATHERED_CUT_COPPER_STAIRS,
    Material.MANGROVE_STAIRS,
  )

  val LOGS = setOf(
    Material.ACACIA_LOG, Material.BIRCH_LOG, Material.DARK_OAK_LOG, Material.JUNGLE_LOG,
    Material.OAK_LOG, Material.SPRUCE_LOG, Material.STRIPPED_ACACIA_LOG, Material.STRIPPED_BIRCH_LOG,
    Material.STRIPPED_DARK_OAK_LOG, Material.STRIPPED_JUNGLE_LOG, Material.STRIPPED_OAK_LOG,
    Material.STRIPPED_SPRUCE_LOG, Material.MANGROVE_LOG, Material.STRIPPED_MANGROVE_LOG,
  )

  val PLANKS = setOf(
    Material.ACACIA_PLANKS, Material.BIRCH_PLANKS, Material.DARK_OAK_PLANKS, Material.JUNGLE_PLANKS,
    Material.OAK_PLANKS, Material.SPRUCE_PLANKS, Material.MANGROVE_PLANKS,
    Material.STRIPPED_ACACIA_WOOD, Material.STRIPPED_BIRCH_WOOD, Material.STRIPPED_DARK_OAK_WOOD,
    Material.STRIPPED_JUNGLE_WOOD, Material.STRIPPED_OAK_WOOD, Material.STRIPPED_SPRUCE_WOOD,
    Material.STRIPPED_MANGROVE_WOOD,
  )

  val LEAVES = setOf(
    Material.ACACIA_LEAVES, Material.AZALEA_LEAVES, Material.BIRCH_LEAVES, Material.DARK_OAK_LEAVES,
    Material.FLOWERING_AZALEA_LEAVES, Material.OAK_LEAVES, Material.JUNGLE_LEAVES, Material.SPRUCE_LEAVES,
    Material.MANGROVE_LEAVES,
  )

  // Takes an ore block and turns it into the non-ore block type it's
  // most similar to. Returns the block itself if given a non-ore.
  fun removeOreFrom(material: Material): Material =
    when (material) {
      Material.COAL_ORE -> Material.STONE
      Material.IRON_ORE -> Material.STONE
      Material.LAPIS_ORE -> Material.STONE
      Material.GOLD_ORE -> Material.STONE
      Material.DIAMOND_ORE -> Material.STONE
      Material.EMERALD_ORE -> Material.STONE
      Material.NETHER_QUARTZ_ORE -> Material.NETHERRACK
      Material.NETHER_GOLD_ORE -> Material.NETHERRACK
      Material.ANCIENT_DEBRIS -> Material.NETHERRACK
      Material.COPPER_ORE -> Material.STONE
      Material.DEEPSLATE_COAL_ORE -> Material.DEEPSLATE
      Material.DEEPSLATE_COPPER_ORE -> Material.DEEPSLATE
      Material.DEEPSLATE_DIAMOND_ORE -> Material.DEEPSLATE
      Material.DEEPSLATE_EMERALD_ORE -> Material.DEEPSLATE
      Material.DEEPSLATE_GOLD_ORE -> Material.DEEPSLATE
      Material.DEEPSLATE_IRON_ORE -> Material.DEEPSLATE
      Material.DEEPSLATE_LAPIS_ORE -> Material.DEEPSLATE
      Material.DEEPSLATE_REDSTONE_ORE -> Material.DEEPSLATE
      else -> material // Default value
    }

}
